version: "3.9"

services:
  api:
    build:
      context: .
      target: api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  # book_enrichment_consumer:
  #   build:
  #     context: .
  #     target: book_enrichment_consumer
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
