services:
  api:
    build: .
    command: >
      sh -c "
        until pg_isready -h ${DB_HOST} -p ${DB_PORT}; do
          echo 'Waiting for Postgres...';
          sleep 1;
        done &&
        python manage.py migrate &&
        python create_superuser.py &&
        python manage.py runserver 0.0.0.0:${API_PORT}
      "
    ports:
      - "${API_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  # book_enrichment_consumer:
  #   build:
  #     context: .
  #     target: book_enrichment_consumer
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
