# Generated by Django 5.2 on 2025-04-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
